### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by AliDeWeb** [HanzoDev1375/Ghostide#16]
when I create a new js project, and I want to remove the first line, which is added to the file by default, app crashes.
and this is the error I get each time.

```
java.lang.ArrayIndexOutOfBoundsException: length=128; index=-1
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureText(GraphicTextRow.java:235)
	at io.github.rosemoe.sora.widget.CodeEditor.measureText(CodeEditor.java:3360)
	at io.github.rosemoe.sora.widget.CodeEditor.updateLineDisplayList(CodeEditor.java:1651)
	at io.github.rosemoe.sora.widget.HwAcceleratedRenderer.drawLineHardwareAccelerated(HwAcceleratedRenderer.java:145)
	at io.github.rosemoe.sora.widget.CodeEditor.drawRows(CodeEditor.java:2319)
	at io.github.rosemoe.sora.widget.CodeEditor.drawView(CodeEditor.java:1390)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:5313)
	at android.view.View.draw(View.java:25177)
	at android.view.View.updateDisplayListIfDirty(View.java:24036)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4764)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4736)
	at android.view.View.updateDisplayListIfDirty(View.java:23982)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.draw(View.java:25180)
	at android.view.View.updateDisplayListIfDirty(View.java:24036)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1179)
	at android.view.View.draw(View.java:25180)
	at com.android.internal.policy.DecorView.draw(DecorView.java:1161)
	at android.view.View.updateDisplayListIfDirty(View.java:24036)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:768)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:774)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:872)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:6051)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5706)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4795)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
	at android.view.Choreographer.doFrame(Choreographer.java:1079)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)


Tue Oct 08 14:08:18 GMT+03:30 2024

```

**Comment by HanzoDev1375** [comment]
@AliDeWeb I know what this problem is and I will try to fix it soon

**Comment by HanzoDev1375** [comment]
fixed in [Commit this](https://github.com/HanzoDev1375/Ghostide/commit/a7da792be0b3cd25461f2fdd4a37950c4f561f50)
