### ISSUE TITLE
Debug build app crash when File manager is opened

### ISSUE THREAD

**Issue by DevAnDroidCoder** [HanzoDev1375/Ghostide#8]
```
Display Metrics:
- Width: 720px
- Height: 1449px
- Density: 320dpi
- Scaled Density: 2.0

Build Information:
- Board: cattail
- Brand: Redmi
- Device ID: QP1A.190711.020
- Display: QP1A.190711.020
- Manufacturer: Xiaomi
- Model: M2006C3MII
- Product: cattail
- Serial Number: unknown

Telephony Information:
- Sim Operator Name: airtel
- Phone Type: GSM
SDK: 29
Android: 10
Model: V12.0.18.0.QCTINXM
App version: 1.6.1

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at Ninja.coder.Ghostemane.code.activities.FileDirActivity$5.onResponse(FileDirActivity.java:410)
	at Ninja.coder.Ghostemane.code.RequestNetworkController$3$2.run(RequestNetworkController.java:162)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)


Sat Sep 21 21:36:31 GMT+05:30 2024
```

**Comment by HanzoDev1375** [comment]
fixed
